### PR TITLE
Interactive HH Model in python

### PR DESCRIPTION
**Pull request by ghost**
Built by @lorforlinux and @drarkadeep

### CODE REVIEW

**Comment by lorforlinux** [comment]
@drarkadeep code looks good, let's include some more info in the notebook before merging the PR?
I believe a references section at the end of the notebook and a bit more commenting in code would be great to have, what do you think?

**Comment by jayanthvarma134** [comment]
And guys, Can we follow a common folder structure as follows:

.gitignore
chapter2/
--> EPSP.ipynb
--> HH_model.ipynb
chapter3/

**Comment by jayanthvarma134** [comment]
Guys, I guess i unknowingly

**Comment by jayanthvarma134** [comment]
Sorry guys, i unkonwingly closed the request. Was a misclick.

**Comment by lorforlinux** [comment]
Sounds good @jayanthvarma134

**Comment by ghost** [comment]
@lorforlinux sure. I will annotate the classes with comments

**Comment by jayanthvarma134** [comment]
@drarkadeep Also, can you add an inline plot (using % matplotlib inline) to show the output within the notebook.

**Comment by ghost** [comment]
@jayanthvarma134 Sure. Will share the updated notebook by tomorrow night :+1:

**Comment by ghost** [comment]
@lorforlinux i have updated the notes and sources

**Comment by lorforlinux** [comment]
@drarkadeep Great work!

**Pull request merged**
