### PR TITLE
Chapter 4: Oja's Learning Rule

### PR DESCRIPTION
**Pull request by dundermain**
@lorforlinux @jayanthvarma134 @jayanthvarma134 
I have added Table 4.3 that is Oja's learning rule to chapter 4.

### CODE REVIEW

**Comment by jayanthvarma134** [comment]
@SynapticLad Amazing job. The notebook looks well decked up with all required markups. Great job, also considering you are not very used to python. 

This one is all good to merge I feel. If anyone else has a specific issue, please do suggest.

**Comment by jayanthvarma134** [comment]
@SynapticLad Just one suggestion struck my mind. 
1. Keep the training loop and plot as separate cells. Each cell doing just one task will look better I think.
2. If you can print the equations within the markups (check latex commands to write math equations), that would be great. 

@lorforlinux @harshitmehra @kgargdun 
Can we please do this in all of our notebooks?
If we feel the markups and documentation can be added later, that's fine, but I feel if we can do it now, it would be done and dusted once and for all and we don't have to come back for these changes again.

**Comment by lorforlinux** [comment]
@jayanthvarma134 that's a good idea, I have updated #6 to have separate cells for calculation and plotting.

**Comment by lorforlinux** [comment]
This PR looks good, merging it!

**Pull request merged**
